USE double_choose;
SET NAMES utf8mb4;
CREATE TABLE student(
  `id` INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `user_name` VARCHAR(128) DEFAULT '' NOT NULL COMMENT '用户名',
  `gender` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '性别，0男 1女',
  `name` VARCHAR(32) DEFAULT '' NOT NULL COMMENT '名字',
  `photo_url` VARCHAR(512) DEFAULT '' NOT NULL COMMENT '照片URL',
  `introduction` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '个人简介',
  `interest` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '兴趣爱好',
  `awards` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '获奖情况',
  `research_direction` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '研究方向',
  `create_time` DATETIME(4) NOT NULL DEFAULT CURRENT_TIMESTAMP(4) COMMENT '创建日期',
  `update_time` DATETIME(4) NOT NULL DEFAULT CURRENT_TIMESTAMP(4) ON UPDATE CURRENT_TIMESTAMP(4) COMMENT '更新日期',
  UNIQUE INDEX uniq_idx_user_name(`user_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='学生信息表';